spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    passowrd:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.H2Dialect
security:
  oauth2:
    client:
      client-id: movieflix
      client-secret: movieflix123
jwt:
  secret: MY-JWT-SECRET
  duration: 86400


